//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Выборы
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionOption
    {
        public int Election_id { get; set; }
        public int Option_id { get; set; }
    
        public virtual Election Election { get; set; }
        public virtual PoolOption PoolOption { get; set; }
        public virtual User User { get; set; }
    }
}
