//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Выборы
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionOptions
    {
        public int Election_id { get; set; }
        public int Option_id { get; set; }
    
        public virtual Elections Elections { get; set; }
        public virtual PoolOptions PoolOptions { get; set; }
        public virtual Users Users { get; set; }
    }
}
